// Re-export barrel for @celebbase/design-tokens.
// tokens.native.ts is generated by scripts/build.ts from tokens.css — do not edit it by hand.

export { tokens, getToken } from './tokens.native.js';
export type { TokenName } from './tokens.native.js';
