-- 0025_backfill_recipe_descriptions.sql
-- Backfill recipes.description for the 180 seeded recipes with factual,
-- ingredient/method-based one-line summaries (no health-efficacy claims).
-- Source of truth: db/seeds/data/*.json. Slug match is identical to the seed
-- loader (db/seeds/loaders/celebrityLoader.ts: `<celeb-slug>-<slugify(title)>`).
-- Idempotent: `description IS NULL` guard skips rows already populated, so this
-- is a no-op on a freshly seeded DB (loader already sets description) and only
-- backfills environments seeded before the loader fix (e.g. staging).
BEGIN;

UPDATE recipes SET description = $$Savory oats with white miso and sesame$$ WHERE slug = 'ariana-grande-miso-oatmeal-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Spiced sweet potato and tempeh hash with avocado$$ WHERE slug = 'ariana-grande-sweet-potato-and-tempeh-breakfast-hash' AND description IS NULL;
UPDATE recipes SET description = $$Matcha chia pudding with blueberries and coconut$$ WHERE slug = 'ariana-grande-matcha-chia-pudding' AND description IS NULL;
UPDATE recipes SET description = $$Rice porridge with shiitake and scallions$$ WHERE slug = 'ariana-grande-japanese-rice-porridge-with-mushrooms' AND description IS NULL;
UPDATE recipes SET description = $$Teriyaki tofu with brown rice and edamame$$ WHERE slug = 'ariana-grande-teriyaki-tofu-rice-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Soba noodles in miso broth with mushrooms$$ WHERE slug = 'ariana-grande-miso-noodle-soup' AND description IS NULL;
UPDATE recipes SET description = $$Deconstructed sushi bowl with edamame and avocado$$ WHERE slug = 'ariana-grande-edamame-avocado-sushi-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Ginger-sesame tempeh in crisp romaine wraps$$ WHERE slug = 'ariana-grande-tempeh-lettuce-wraps' AND description IS NULL;
UPDATE recipes SET description = $$Tofu stir-fry with broccoli and snow peas$$ WHERE slug = 'ariana-grande-veggie-stir-fry-with-tofu' AND description IS NULL;
UPDATE recipes SET description = $$Coconut sweet potato curry over jasmine rice$$ WHERE slug = 'ariana-grande-sweet-potato-curry' AND description IS NULL;
UPDATE recipes SET description = $$Rice bowl with shiitake, edamame, and nori$$ WHERE slug = 'ariana-grande-mushroom-and-edamame-donburi' AND description IS NULL;
UPDATE recipes SET description = $$Rice noodles with tempeh, bok choy, and lime$$ WHERE slug = 'ariana-grande-tempeh-and-vegetable-noodle-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Edamame hummus with crunchy veggie sticks$$ WHERE slug = 'ariana-grande-edamame-hummus-with-veggie-sticks' AND description IS NULL;
UPDATE recipes SET description = $$Rice cakes with sweet miso glaze and nori$$ WHERE slug = 'ariana-grande-miso-glazed-rice-cakes' AND description IS NULL;
UPDATE recipes SET description = $$Spiced roasted chickpeas with almonds and cranberries$$ WHERE slug = 'ariana-grande-roasted-chickpea-trail-mix' AND description IS NULL;
UPDATE recipes SET description = $$Banana bites with almond butter and cacao nibs$$ WHERE slug = 'ariana-grande-almond-butter-banana-bites' AND description IS NULL;
UPDATE recipes SET description = $$Matcha banana smoothie with almond butter$$ WHERE slug = 'ariana-grande-matcha-banana-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Acai berry smoothie with banana and chia$$ WHERE slug = 'ariana-grande-berry-acai-power-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Quinoa with almond milk, banana, and walnuts$$ WHERE slug = 'beyonce-quinoa-breakfast-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Sweet potato toast with avocado and lime$$ WHERE slug = 'beyonce-sweet-potato-toast-with-avocado' AND description IS NULL;
UPDATE recipes SET description = $$Overnight oats with chia and strawberries$$ WHERE slug = 'beyonce-overnight-oats-with-berries' AND description IS NULL;
UPDATE recipes SET description = $$Oat-banana pancakes blended with spinach and blueberries$$ WHERE slug = 'beyonce-green-power-pancakes' AND description IS NULL;
UPDATE recipes SET description = $$Spiced red lentil and sweet potato soup$$ WHERE slug = 'beyonce-lentil-and-sweet-potato-soup' AND description IS NULL;
UPDATE recipes SET description = $$Quinoa-chickpea salad with avocado and lemon$$ WHERE slug = 'beyonce-chickpea-and-quinoa-power-salad' AND description IS NULL;
UPDATE recipes SET description = $$Black bean tacos with guacamole and salsa$$ WHERE slug = 'beyonce-black-bean-tacos' AND description IS NULL;
UPDATE recipes SET description = $$Kale Caesar with crispy chickpea croutons$$ WHERE slug = 'beyonce-kale-caesar-with-chickpea-croutons' AND description IS NULL;
UPDATE recipes SET description = $$Peppers stuffed with quinoa and black beans$$ WHERE slug = 'beyonce-stuffed-bell-peppers-with-quinoa-and-black-beans' AND description IS NULL;
UPDATE recipes SET description = $$Coconut lentil curry over brown rice$$ WHERE slug = 'beyonce-coconut-curry-lentil-stew' AND description IS NULL;
UPDATE recipes SET description = $$Spiced cauliflower and chickpea bake with tahini$$ WHERE slug = 'beyonce-cauliflower-and-chickpea-bake' AND description IS NULL;
UPDATE recipes SET description = $$Mushroom-lentil bolognese over whole wheat pasta$$ WHERE slug = 'beyonce-mushroom-and-lentil-bolognese' AND description IS NULL;
UPDATE recipes SET description = $$Smoky paprika roasted chickpeas$$ WHERE slug = 'beyonce-spiced-roasted-chickpeas' AND description IS NULL;
UPDATE recipes SET description = $$Date and oat balls with almond butter$$ WHERE slug = 'beyonce-energy-date-balls' AND description IS NULL;
UPDATE recipes SET description = $$Apple slices with cashew butter and cinnamon$$ WHERE slug = 'beyonce-apple-slices-with-cashew-butter' AND description IS NULL;
UPDATE recipes SET description = $$Fresh veggies with hummus$$ WHERE slug = 'beyonce-veggies-and-hummus-plate' AND description IS NULL;
UPDATE recipes SET description = $$Mango-pineapple green smoothie with spinach$$ WHERE slug = 'beyonce-tropical-green-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Chocolate peanut butter smoothie with dates$$ WHERE slug = 'beyonce-chocolate-peanut-butter-power-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Egg whites and avocado on whole-wheat toast$$ WHERE slug = 'cristiano-ronaldo-egg-white-and-avocado-breakfast-plate' AND description IS NULL;
UPDATE recipes SET description = $$Protein steel-cut oats with mixed berries$$ WHERE slug = 'cristiano-ronaldo-protein-oatmeal-with-berries' AND description IS NULL;
UPDATE recipes SET description = $$Eggs and spinach on whole-wheat toast$$ WHERE slug = 'cristiano-ronaldo-whole-wheat-toast-with-eggs-and-spinach' AND description IS NULL;
UPDATE recipes SET description = $$Turkey and egg-white scramble with sweet potato$$ WHERE slug = 'cristiano-ronaldo-sweet-potato-and-turkey-sausage-scramble' AND description IS NULL;
UPDATE recipes SET description = $$Grilled chicken and quinoa with broccoli$$ WHERE slug = 'cristiano-ronaldo-grilled-chicken-and-quinoa-power-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Seared tuna with brown rice and asparagus$$ WHERE slug = 'cristiano-ronaldo-tuna-steak-with-brown-rice-and-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Grilled chicken Caesar without croutons$$ WHERE slug = 'cristiano-ronaldo-chicken-caesar-salad-no-croutons' AND description IS NULL;
UPDATE recipes SET description = $$Ground turkey with sweet potato and broccoli$$ WHERE slug = 'cristiano-ronaldo-turkey-and-sweet-potato-meal-prep-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Grilled salmon with asparagus and dill$$ WHERE slug = 'cristiano-ronaldo-grilled-salmon-with-asparagus' AND description IS NULL;
UPDATE recipes SET description = $$Lean sirloin with brown rice and green beans$$ WHERE slug = 'cristiano-ronaldo-lean-beef-sirloin-with-brown-rice' AND description IS NULL;
UPDATE recipes SET description = $$Baked cod with zucchini and peppers$$ WHERE slug = 'cristiano-ronaldo-baked-cod-with-roasted-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Chicken breast with sweet potato mash$$ WHERE slug = 'cristiano-ronaldo-chicken-breast-with-sweet-potato-mash' AND description IS NULL;
UPDATE recipes SET description = $$Cottage cheese with berries and pumpkin seeds$$ WHERE slug = 'cristiano-ronaldo-cottage-cheese-and-fruit-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Greek yogurt with honey and walnuts$$ WHERE slug = 'cristiano-ronaldo-greek-yogurt-with-honey-and-walnuts' AND description IS NULL;
UPDATE recipes SET description = $$Hard-boiled eggs with sliced avocado$$ WHERE slug = 'cristiano-ronaldo-hard-boiled-eggs-with-avocado' AND description IS NULL;
UPDATE recipes SET description = $$Whey protein shake with banana$$ WHERE slug = 'cristiano-ronaldo-protein-shake-with-banana' AND description IS NULL;
UPDATE recipes SET description = $$Whey, banana, and peanut butter shake$$ WHERE slug = 'cristiano-ronaldo-post-workout-recovery-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Whey protein smoothie with mixed berries$$ WHERE slug = 'cristiano-ronaldo-berry-protein-blast' AND description IS NULL;
UPDATE recipes SET description = $$Pan-seared sirloin with egg whites and avocado$$ WHERE slug = 'dwayne-johnson-steak-and-eggs-breakfast' AND description IS NULL;
UPDATE recipes SET description = $$Baked cod with sweet potato and asparagus$$ WHERE slug = 'dwayne-johnson-cod-and-sweet-potato-breakfast' AND description IS NULL;
UPDATE recipes SET description = $$Egg-white omelette with mushrooms, spinach, and peppers$$ WHERE slug = 'dwayne-johnson-egg-white-omelette-with-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Rolled oats with egg whites and blueberries$$ WHERE slug = 'dwayne-johnson-protein-oats-with-egg-whites' AND description IS NULL;
UPDATE recipes SET description = $$Baked cod with white rice and broccoli$$ WHERE slug = 'dwayne-johnson-cod-with-white-rice-and-broccoli' AND description IS NULL;
UPDATE recipes SET description = $$Chicken breast with basmati rice and asparagus$$ WHERE slug = 'dwayne-johnson-chicken-breast-with-basmati-rice' AND description IS NULL;
UPDATE recipes SET description = $$Ground bison and rice with mushrooms$$ WHERE slug = 'dwayne-johnson-ground-bison-and-rice-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Turkey breast with sweet potato and green beans$$ WHERE slug = 'dwayne-johnson-turkey-breast-and-sweet-potato-plate' AND description IS NULL;
UPDATE recipes SET description = $$Grilled sirloin with potato and broccoli$$ WHERE slug = 'dwayne-johnson-grilled-sirloin-with-potato-and-veggies' AND description IS NULL;
UPDATE recipes SET description = $$Baked cod with rice and mixed greens$$ WHERE slug = 'dwayne-johnson-cod-with-rice-and-mixed-greens' AND description IS NULL;
UPDATE recipes SET description = $$Chicken and quinoa with Brussels sprouts$$ WHERE slug = 'dwayne-johnson-chicken-and-quinoa-power-plate' AND description IS NULL;
UPDATE recipes SET description = $$Salmon with sweet potato mash and asparagus$$ WHERE slug = 'dwayne-johnson-salmon-with-sweet-potato-mash' AND description IS NULL;
UPDATE recipes SET description = $$Rice cakes with peanut butter and honey$$ WHERE slug = 'dwayne-johnson-peanut-butter-rice-cakes' AND description IS NULL;
UPDATE recipes SET description = $$Egg whites on Ezekiel toast$$ WHERE slug = 'dwayne-johnson-egg-whites-and-toast' AND description IS NULL;
UPDATE recipes SET description = $$Whey protein pudding with strawberries$$ WHERE slug = 'dwayne-johnson-protein-pudding' AND description IS NULL;
UPDATE recipes SET description = $$Almonds with dried apricots$$ WHERE slug = 'dwayne-johnson-almonds-and-dried-fruit' AND description IS NULL;
UPDATE recipes SET description = $$High-calorie shake with oats and peanut butter$$ WHERE slug = 'dwayne-johnson-mass-gain-shake' AND description IS NULL;
UPDATE recipes SET description = $$Chocolate whey smoothie with almond butter$$ WHERE slug = 'dwayne-johnson-chocolate-protein-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Smoked salmon and avocado on Ezekiel toast$$ WHERE slug = 'gwyneth-paltrow-avocado-and-smoked-salmon-toast' AND description IS NULL;
UPDATE recipes SET description = $$Frittata with spinach, zucchini, and leek$$ WHERE slug = 'gwyneth-paltrow-green-vegetable-frittata' AND description IS NULL;
UPDATE recipes SET description = $$Grain-free nut granola with coconut yogurt$$ WHERE slug = 'gwyneth-paltrow-grain-free-granola-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Sweet potato and kale hash with eggs$$ WHERE slug = 'gwyneth-paltrow-sweet-potato-and-kale-hash-with-eggs' AND description IS NULL;
UPDATE recipes SET description = $$Wild salmon over arugula with fennel$$ WHERE slug = 'gwyneth-paltrow-wild-salmon-and-arugula-salad' AND description IS NULL;
UPDATE recipes SET description = $$Bone broth soup with sweet potato and kale$$ WHERE slug = 'gwyneth-paltrow-bone-broth-and-vegetable-soup' AND description IS NULL;
UPDATE recipes SET description = $$Seasoned turkey and avocado in lettuce wraps$$ WHERE slug = 'gwyneth-paltrow-turkey-and-avocado-lettuce-wraps' AND description IS NULL;
UPDATE recipes SET description = $$Roasted beets with goat cheese and walnuts$$ WHERE slug = 'gwyneth-paltrow-roasted-beet-and-goat-cheese-salad' AND description IS NULL;
UPDATE recipes SET description = $$Herb salmon with asparagus and zucchini$$ WHERE slug = 'gwyneth-paltrow-herb-crusted-salmon-with-roasted-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Chicken stir-fry with broccoli and peppers$$ WHERE slug = 'gwyneth-paltrow-chicken-and-vegetable-stir-fry' AND description IS NULL;
UPDATE recipes SET description = $$Cauliflower-rice risotto with mushrooms$$ WHERE slug = 'gwyneth-paltrow-cauliflower-rice-risotto-with-mushrooms' AND description IS NULL;
UPDATE recipes SET description = $$Lemon-herb chicken with sweet potato$$ WHERE slug = 'gwyneth-paltrow-lemon-herb-roasted-chicken-with-sweet-potato' AND description IS NULL;
UPDATE recipes SET description = $$Date and almond butter bites$$ WHERE slug = 'gwyneth-paltrow-almond-crusted-protein-bites' AND description IS NULL;
UPDATE recipes SET description = $$Cucumber rounds topped with avocado$$ WHERE slug = 'gwyneth-paltrow-cucumber-avocado-bites' AND description IS NULL;
UPDATE recipes SET description = $$Almonds and walnuts with blueberries$$ WHERE slug = 'gwyneth-paltrow-mixed-nuts-and-berries' AND description IS NULL;
UPDATE recipes SET description = $$Warm bone broth with turmeric$$ WHERE slug = 'gwyneth-paltrow-bone-broth-sipping-cup' AND description IS NULL;
UPDATE recipes SET description = $$Green smoothie with cucumber, apple, and ginger$$ WHERE slug = 'gwyneth-paltrow-green-detox-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Berry collagen smoothie with almond butter$$ WHERE slug = 'gwyneth-paltrow-berry-collagen-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Eggs and smoked salmon with avocado$$ WHERE slug = 'jennifer-aniston-smoked-salmon-and-egg-plate' AND description IS NULL;
UPDATE recipes SET description = $$Greek yogurt parfait with granola and berries$$ WHERE slug = 'jennifer-aniston-greek-yogurt-parfait' AND description IS NULL;
UPDATE recipes SET description = $$Omelette with spinach, tomato, and feta$$ WHERE slug = 'jennifer-aniston-veggie-omelette-with-feta' AND description IS NULL;
UPDATE recipes SET description = $$Banana coffee smoothie with collagen$$ WHERE slug = 'jennifer-aniston-collagen-coffee-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Salmon salad with olives, feta, and cucumber$$ WHERE slug = 'jennifer-aniston-mediterranean-salmon-salad' AND description IS NULL;
UPDATE recipes SET description = $$Quinoa with grilled zucchini and peppers$$ WHERE slug = 'jennifer-aniston-quinoa-and-grilled-veggie-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Tuna nicoise with egg, beans, and olives$$ WHERE slug = 'jennifer-aniston-tuna-ni-oise-salad' AND description IS NULL;
UPDATE recipes SET description = $$Sardines and avocado on sourdough$$ WHERE slug = 'jennifer-aniston-sardine-and-avocado-toast' AND description IS NULL;
UPDATE recipes SET description = $$Baked salmon with asparagus and tomatoes$$ WHERE slug = 'jennifer-aniston-baked-salmon-with-roasted-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Paprika shrimp over quinoa and arugula$$ WHERE slug = 'jennifer-aniston-shrimp-and-quinoa-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Herb-baked cod with artichokes and olives$$ WHERE slug = 'jennifer-aniston-herb-baked-cod-with-artichokes' AND description IS NULL;
UPDATE recipes SET description = $$Grilled chicken with cucumber-feta salad$$ WHERE slug = 'jennifer-aniston-grilled-chicken-with-mediterranean-salad' AND description IS NULL;
UPDATE recipes SET description = $$Almonds with dark chocolate$$ WHERE slug = 'jennifer-aniston-almonds-and-dark-chocolate' AND description IS NULL;
UPDATE recipes SET description = $$Greek yogurt with cucumber and dill$$ WHERE slug = 'jennifer-aniston-greek-yogurt-with-cucumber-and-dill' AND description IS NULL;
UPDATE recipes SET description = $$Olives and hummus with veggie sticks$$ WHERE slug = 'jennifer-aniston-olives-and-hummus-plate' AND description IS NULL;
UPDATE recipes SET description = $$Apple slices with walnuts$$ WHERE slug = 'jennifer-aniston-apple-and-walnut-snack' AND description IS NULL;
UPDATE recipes SET description = $$Banana-spinach smoothie with collagen and walnuts$$ WHERE slug = 'jennifer-aniston-green-mediterranean-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Mixed berry smoothie with flaxseed$$ WHERE slug = 'jennifer-aniston-berry-and-flax-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Fresh fruit with walnuts and pumpkin seeds$$ WHERE slug = 'joaquin-phoenix-raw-fruit-and-nut-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Raw oat muesli with apple and seeds$$ WHERE slug = 'joaquin-phoenix-raw-oat-and-seed-muesli' AND description IS NULL;
UPDATE recipes SET description = $$Avocado and sprouts on Ezekiel toast$$ WHERE slug = 'joaquin-phoenix-avocado-and-sprout-toast' AND description IS NULL;
UPDATE recipes SET description = $$Coconut chia pudding with mango$$ WHERE slug = 'joaquin-phoenix-chia-pudding-with-mango' AND description IS NULL;
UPDATE recipes SET description = $$Nori wraps with hummus and raw veggies$$ WHERE slug = 'joaquin-phoenix-raw-veggie-nori-wraps' AND description IS NULL;
UPDATE recipes SET description = $$Massaged kale salad with avocado and seeds$$ WHERE slug = 'joaquin-phoenix-raw-kale-and-avocado-salad' AND description IS NULL;
UPDATE recipes SET description = $$Lentils with raw veggies and tahini$$ WHERE slug = 'joaquin-phoenix-lentil-and-raw-veggie-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Zucchini noodles with pine-nut pesto$$ WHERE slug = 'joaquin-phoenix-zucchini-noodle-and-pesto-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Sweet potato and black bean chili$$ WHERE slug = 'joaquin-phoenix-sweet-potato-and-black-bean-chili' AND description IS NULL;
UPDATE recipes SET description = $$Raw veggie noodles with cashew-lime sauce$$ WHERE slug = 'joaquin-phoenix-raw-cashew-pad-thai' AND description IS NULL;
UPDATE recipes SET description = $$Roasted cauliflower and chickpeas with tahini$$ WHERE slug = 'joaquin-phoenix-roasted-cauliflower-with-chickpeas-and-tahini' AND description IS NULL;
UPDATE recipes SET description = $$Simple lentil soup with carrot and celery$$ WHERE slug = 'joaquin-phoenix-simple-vegetable-and-lentil-soup' AND description IS NULL;
UPDATE recipes SET description = $$No-bake cashew and date bites$$ WHERE slug = 'joaquin-phoenix-raw-cashew-and-date-bites' AND description IS NULL;
UPDATE recipes SET description = $$Raw veggie sticks with tahini$$ WHERE slug = 'joaquin-phoenix-sliced-veggies-with-tahini' AND description IS NULL;
UPDATE recipes SET description = $$Apple, orange, and kiwi plate$$ WHERE slug = 'joaquin-phoenix-fresh-fruit-plate' AND description IS NULL;
UPDATE recipes SET description = $$Mixed nuts with hemp and pumpkin seeds$$ WHERE slug = 'joaquin-phoenix-nuts-and-seeds-mix' AND description IS NULL;
UPDATE recipes SET description = $$Green apple and ginger smoothie$$ WHERE slug = 'joaquin-phoenix-green-apple-ginger-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Raw cacao banana smoothie with dates$$ WHERE slug = 'joaquin-phoenix-raw-cacao-and-banana-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Egg scramble with sweet potato and spinach$$ WHERE slug = 'lebron-james-power-egg-scramble-with-sweet-potato' AND description IS NULL;
UPDATE recipes SET description = $$Oat-protein pancakes with banana and blueberries$$ WHERE slug = 'lebron-james-protein-pancakes-with-berries' AND description IS NULL;
UPDATE recipes SET description = $$Smoked salmon, egg, and avocado toast$$ WHERE slug = 'lebron-james-avocado-toast-with-smoked-salmon-and-eggs' AND description IS NULL;
UPDATE recipes SET description = $$Steel-cut oats with almond butter and banana$$ WHERE slug = 'lebron-james-steel-cut-oats-with-nut-butter' AND description IS NULL;
UPDATE recipes SET description = $$Grilled chicken and avocado wrap with spinach$$ WHERE slug = 'lebron-james-grilled-chicken-and-avocado-wrap' AND description IS NULL;
UPDATE recipes SET description = $$Salmon and brown rice bowl with greens$$ WHERE slug = 'lebron-james-salmon-rice-bowl-with-greens' AND description IS NULL;
UPDATE recipes SET description = $$Peppers stuffed with turkey and quinoa$$ WHERE slug = 'lebron-james-turkey-and-quinoa-stuffed-peppers' AND description IS NULL;
UPDATE recipes SET description = $$Chicken noodle soup in bone broth$$ WHERE slug = 'lebron-james-chicken-bone-broth-noodle-soup' AND description IS NULL;
UPDATE recipes SET description = $$Herb chicken with quinoa-tomato salad$$ WHERE slug = 'lebron-james-herb-grilled-chicken-with-quinoa-salad' AND description IS NULL;
UPDATE recipes SET description = $$Salmon with sweet potato and broccoli$$ WHERE slug = 'lebron-james-pan-seared-salmon-with-sweet-potato-and-broccoli' AND description IS NULL;
UPDATE recipes SET description = $$Lean steak with sprouts and sweet potato$$ WHERE slug = 'lebron-james-lean-steak-with-roasted-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Baked chicken with carrot and sweet potato$$ WHERE slug = 'lebron-james-baked-chicken-thighs-with-root-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Rice cake with almond butter and banana$$ WHERE slug = 'lebron-james-almond-butter-and-banana-rice-cake' AND description IS NULL;
UPDATE recipes SET description = $$Nuts, cranberries, and dark chocolate trail mix$$ WHERE slug = 'lebron-james-trail-mix-power-pack' AND description IS NULL;
UPDATE recipes SET description = $$Protein smoothie bowl with granola and strawberries$$ WHERE slug = 'lebron-james-protein-bar-smoothie-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Greek yogurt shake with berries and honey$$ WHERE slug = 'lebron-james-greek-yogurt-protein-shake' AND description IS NULL;
UPDATE recipes SET description = $$Spinach-banana recovery smoothie with protein$$ WHERE slug = 'lebron-james-green-recovery-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Mango-pineapple smoothie with protein$$ WHERE slug = 'lebron-james-tropical-performance-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Berry smoothie bowl with granola and chia$$ WHERE slug = 'natalie-portman-berry-and-granola-smoothie-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Mashed chickpea and avocado toast$$ WHERE slug = 'natalie-portman-avocado-toast-with-chickpea-spread' AND description IS NULL;
UPDATE recipes SET description = $$Turmeric tofu scramble with peppers and spinach$$ WHERE slug = 'natalie-portman-tofu-scramble-with-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Overnight oats with walnuts and banana$$ WHERE slug = 'natalie-portman-overnight-oats-with-walnuts-and-banana' AND description IS NULL;
UPDATE recipes SET description = $$Hearty lentil stew with kale and carrot$$ WHERE slug = 'natalie-portman-lentil-and-vegetable-stew' AND description IS NULL;
UPDATE recipes SET description = $$Quinoa tabbouleh with parsley and mint$$ WHERE slug = 'natalie-portman-quinoa-tabbouleh' AND description IS NULL;
UPDATE recipes SET description = $$Chickpea and roasted veggie wrap with hummus$$ WHERE slug = 'natalie-portman-chickpea-and-roasted-veggie-wrap' AND description IS NULL;
UPDATE recipes SET description = $$Tempeh bowl with sweet potato and tahini$$ WHERE slug = 'natalie-portman-tempeh-buddha-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Coconut chickpea curry over basmati rice$$ WHERE slug = 'natalie-portman-coconut-chickpea-curry' AND description IS NULL;
UPDATE recipes SET description = $$Sweet potatoes stuffed with black beans$$ WHERE slug = 'natalie-portman-stuffed-sweet-potatoes-with-black-beans' AND description IS NULL;
UPDATE recipes SET description = $$Mushroom-walnut bolognese over whole wheat pasta$$ WHERE slug = 'natalie-portman-mushroom-and-walnut-bolognese' AND description IS NULL;
UPDATE recipes SET description = $$Tofu stir-fry with broccoli over brown rice$$ WHERE slug = 'natalie-portman-tofu-stir-fry-with-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Date and almond butter oat bites$$ WHERE slug = 'natalie-portman-almond-energy-bites' AND description IS NULL;
UPDATE recipes SET description = $$Hummus with carrot, cucumber, and peppers$$ WHERE slug = 'natalie-portman-hummus-and-veggie-plate' AND description IS NULL;
UPDATE recipes SET description = $$Apple slices with peanut butter$$ WHERE slug = 'natalie-portman-apple-with-peanut-butter' AND description IS NULL;
UPDATE recipes SET description = $$Nuts with cranberries and raisins$$ WHERE slug = 'natalie-portman-trail-mix-with-dried-fruit' AND description IS NULL;
UPDATE recipes SET description = $$Banana-spinach smoothie with hemp seeds$$ WHERE slug = 'natalie-portman-green-goddess-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Mango turmeric smoothie with ginger$$ WHERE slug = 'natalie-portman-mango-turmeric-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Steel-cut oats with banana, walnuts, and hemp$$ WHERE slug = 'tom-brady-tb12-sunrise-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Eggs with avocado, mushrooms, and sweet potato$$ WHERE slug = 'tom-brady-avocado-and-egg-bowl-no-nightshades' AND description IS NULL;
UPDATE recipes SET description = $$Plant-protein smoothie bowl with granola$$ WHERE slug = 'tom-brady-protein-smoothie-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Quinoa porridge with chia and hemp seeds$$ WHERE slug = 'tom-brady-quinoa-porridge-with-seeds' AND description IS NULL;
UPDATE recipes SET description = $$Wild salmon and brown rice with avocado$$ WHERE slug = 'tom-brady-wild-salmon-and-brown-rice-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Bone broth bowl with root vegetables$$ WHERE slug = 'tom-brady-bone-broth-and-vegetable-bowl' AND description IS NULL;
UPDATE recipes SET description = $$Chicken and quinoa salad with spinach$$ WHERE slug = 'tom-brady-chicken-and-quinoa-salad' AND description IS NULL;
UPDATE recipes SET description = $$Sweet potato and red lentil soup$$ WHERE slug = 'tom-brady-sweet-potato-and-lentil-soup' AND description IS NULL;
UPDATE recipes SET description = $$Herb chicken with sweet potato and carrot$$ WHERE slug = 'tom-brady-herb-grilled-chicken-with-root-vegetables' AND description IS NULL;
UPDATE recipes SET description = $$Baked salmon with broccoli and kale$$ WHERE slug = 'tom-brady-baked-salmon-with-steamed-greens' AND description IS NULL;
UPDATE recipes SET description = $$Butternut squash stuffed with quinoa and pecans$$ WHERE slug = 'tom-brady-quinoa-stuffed-butternut-squash' AND description IS NULL;
UPDATE recipes SET description = $$Lean chicken with brown rice and asparagus$$ WHERE slug = 'tom-brady-lean-chicken-and-brown-rice-plate' AND description IS NULL;
UPDATE recipes SET description = $$Date and almond butter oat bites$$ WHERE slug = 'tom-brady-tb12-protein-bites' AND description IS NULL;
UPDATE recipes SET description = $$Avocado with pumpkin seeds and salt$$ WHERE slug = 'tom-brady-avocado-and-seeds-snack' AND description IS NULL;
UPDATE recipes SET description = $$Almonds and pecans with cranberries$$ WHERE slug = 'tom-brady-mixed-nuts-and-dried-fruit' AND description IS NULL;
UPDATE recipes SET description = $$Warm bone broth with turmeric$$ WHERE slug = 'tom-brady-bone-broth-cup' AND description IS NULL;
UPDATE recipes SET description = $$Plant-protein smoothie with spinach and almond butter$$ WHERE slug = 'tom-brady-tb12-performance-smoothie' AND description IS NULL;
UPDATE recipes SET description = $$Blueberry smoothie with flaxseed and turmeric$$ WHERE slug = 'tom-brady-blueberry-anti-inflammatory-smoothie' AND description IS NULL;

COMMIT;
