// Auto-generated by CHORE-006 implementation
import { describe, it, expect, jest, beforeAll, afterAll } from '@jest/globals';
import Fastify, { FastifyInstance } from 'fastify';
import rateLimit from '@fastify/rate-limit';
import { SignJWT, generateKeyPair, exportJWK, createLocalJWKSet, jwtVerify, type JWK } from 'jose';
import type pg from 'pg';
import { UnauthorizedError } from '@celebbase/service-core';
import type { AuthProvider, AuthTokens, AuthTokenSubject, IdTokenPayload } from '../../src/services/auth.service.js';

// ── 저장소 mock ──────────────────────────────────────────────

const mockFindByCognitoSub = jest.fn();
const mockFindByEmail = jest.fn();
const mockFindAndUpdateCognitoSubByEmail = jest.fn();
const mockCreate = jest.fn();
const mockUpdateCognitoSub = jest.fn();

jest.unstable_mockModule('../../src/repositories/user.repository.js', () => ({
  findByCognitoSub: mockFindByCognitoSub,
  findByEmail: mockFindByEmail,
  findAndUpdateCognitoSubByEmail: mockFindAndUpdateCognitoSubByEmail,
  create: mockCreate,
  updateCognitoSub: mockUpdateCognitoSub,
}));

const mockInsert = jest.fn();
const mockRevokeForRotation = jest.fn();
const mockFindMetadata = jest.fn();
const mockRevokeForLogout = jest.fn();
const mockRevokeChainForLogout = jest.fn();
const mockRevokeAllByUser = jest.fn();

jest.unstable_mockModule('../../src/repositories/refresh-token.repository.js', () => ({
  insert: mockInsert,
  revokeForRotation: mockRevokeForRotation,
  findMetadata: mockFindMetadata,
  revokeForLogout: mockRevokeForLogout,
  revokeChainForLogout: mockRevokeChainForLogout,
  revokeAllByUser: mockRevokeAllByUser,
}));

const { authRoutes } = await import('../../src/routes/auth.routes.js');

// ── 로컬 JWKS 세팅 ───────────────────────────────────────────

const TEST_ISSUER = 'https://cognito-idp.us-west-2.amazonaws.com/us-west-2_TESTPOOL';
const TEST_CLIENT_ID = 'test-client-id';

let privateKeyA: CryptoKey;
let publicKeyA: CryptoKey;
let kidA: string;
let privateKeyB: CryptoKey;
let kidB: string;
let localJwks: ReturnType<typeof createLocalJWKSet>;

beforeAll(async () => {
  const pairA = await generateKeyPair('RS256');
  privateKeyA = pairA.privateKey;
  publicKeyA = pairA.publicKey;

  const pairB = await generateKeyPair('RS256');
  privateKeyB = pairB.privateKey;

  kidA = 'key-a';
  kidB = 'key-b';

  const jwkA = { ...(await exportJWK(publicKeyA)), kid: kidA } as JWK;
  const jwkB = { ...(await exportJWK(pairB.publicKey)), kid: kidB } as JWK;
  localJwks = createLocalJWKSet({ keys: [jwkA, jwkB] });
});

class LocalCognitoTestProvider implements AuthProvider {

  async verifyIdToken(idToken: string): Promise<IdTokenPayload> {
    try {
      const { payload } = await jwtVerify(idToken, localJwks, {
        issuer: TEST_ISSUER,
        audience: TEST_CLIENT_ID,
        algorithms: ['RS256'],
        clockTolerance: 60,
      });
      if (payload['token_use'] !== 'id') {
        throw new UnauthorizedError('Expected id token');
      }
      if (typeof payload.sub !== 'string' || !payload.sub) {
        throw new UnauthorizedError('Missing sub claim');
      }
      if (typeof payload['email'] !== 'string' || !payload['email']) {
        throw new UnauthorizedError('Missing email claim');
      }
      return { sub: payload.sub, email: payload['email'] as string };
    } catch (err) {
      if (err instanceof UnauthorizedError) throw err;
      throw new UnauthorizedError('Invalid or expired id token');
    }
  }

  async issueTokens(client: pg.Pool | pg.PoolClient, subject: AuthTokenSubject): Promise<AuthTokens> {
    const { issueInternalTokens } = await import('../../src/services/auth.service.js');
    return issueInternalTokens(client as pg.Pool, subject);
  }
}

interface CapturedLog { event?: string; [key: string]: unknown; }

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function makeCaptureLogger(captured: CapturedLog[]): any {
  const logger = {
    level: 'info',
    silent: () => undefined,
    info: (obj: unknown): void => {
      if (typeof obj === 'object' && obj !== null) captured.push(obj as CapturedLog);
    },
    warn: (obj: unknown): void => {
      if (typeof obj === 'object' && obj !== null) captured.push(obj as CapturedLog);
    },
    error: () => undefined,
    debug: () => undefined,
    trace: () => undefined,
    fatal: () => undefined,
    child: () => logger,
  };
  return logger;
}

async function buildApp(provider: AuthProvider): Promise<FastifyInstance> {
  const captured: CapturedLog[] = [];
  const app = Fastify({
    loggerInstance: makeCaptureLogger(captured),
    disableRequestLogging: true,
  });
  await app.register(rateLimit, { global: false });
  await app.register(authRoutes, {
    pool: {} as pg.Pool,
    authProvider: provider,
  });
  return app;
}

async function mintIdToken(overrides: {
  kid?: string;
  issuer?: string;
  audience?: string;
  tokenUse?: string;
  sub?: string | null;
  email?: string | null;
  expiresIn?: string | number;
  privateKey?: CryptoKey;
} = {}): Promise<string> {
  const {
    kid = kidA,
    issuer = TEST_ISSUER,
    audience = TEST_CLIENT_ID,
    tokenUse = 'id',
    sub = 'cognito-sub-real-123',
    email = 'test@example.com',
    expiresIn = '5m',
    privateKey = privateKeyA,
  } = overrides;

  const payload: Record<string, unknown> = { token_use: tokenUse };
  if (email !== null) payload['email'] = email;

  let builder = new SignJWT(payload)
    .setProtectedHeader({ alg: 'RS256', kid })
    .setIssuer(issuer)
    .setAudience(audience)
    .setIssuedAt()
    .setExpirationTime(expiresIn);

  if (sub !== null) builder = builder.setSubject(sub);

  return builder.sign(privateKey);
}

// ── 테스트 케이스 ─────────────────────────────────────────────────────────

describe('Cognito AuthProvider Integration', () => {
  let app: FastifyInstance;
  beforeAll(async () => {
    const provider = new LocalCognitoTestProvider();
    app = await buildApp(provider);
    await app.ready();
  });
  afterAll(async () => {
    await app.close();
  });

  it('T1: valid id_token login', async () => {
    const token = await mintIdToken();
    mockFindByCognitoSub.mockResolvedValueOnce({
      id: 'user-id-1',
      email: 'test@example.com',
      cognito_sub: 'cognito-sub-real-123',
      display_name: 'Test',
      deleted_at: null,
    });
    mockInsert.mockResolvedValueOnce(undefined);
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(200);
    const body = res.json();
    expect(body).toHaveProperty('access_token');
    expect(body).toHaveProperty('refresh_token');
  });

  it('T2: access_token should 401', async () => {
    const token = await mintIdToken({ tokenUse: 'access' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T3: expired token 401', async () => {
    const past = Math.floor(Date.now() / 1000) - 200;
    const token = await mintIdToken({ expiresIn: past });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T4: wrong issuer 401', async () => {
    const token = await mintIdToken({ issuer: 'https://fake-issuer.example.com' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T5: kid rotation both succeed', async () => {
    const tokenB = await mintIdToken({ kid: kidB, privateKey: privateKeyB });
    mockFindByCognitoSub.mockResolvedValue({ id: 'x', email: 'test@example.com', cognito_sub: 'cognito-sub-real-123', display_name: 'Test', deleted_at: null });
    mockInsert.mockResolvedValue(undefined);
    let res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenB } });
    expect(res.statusCode).toBe(200);

    const tokenA = await mintIdToken({ kid: kidA });
    res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenA } });
    expect(res.statusCode).toBe(200);
  });

  it('T6: clock skew tolerance', async () => {
    const expMinus30 = Math.floor(Date.now() / 1000) - 30;
    const tokenNear = await mintIdToken({ expiresIn: expMinus30 });
    let res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenNear } });
    expect(res.statusCode).toBe(200);

    const expMinus70 = Math.floor(Date.now() / 1000) - 70;
    const tokenFar = await mintIdToken({ expiresIn: expMinus70 });
    res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenFar } });
    expect(res.statusCode).toBe(401);
  });

  it('T7: wrong audience 401', async () => {
    const token = await mintIdToken({ audience: 'wrong-client-id' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T8: missing sub claim 401', async () => {
    const token = await mintIdToken({ sub: null });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T9: missing email claim 401', async () => {
    const token = await mintIdToken({ email: null });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T10: wrong kid (key not in JWKS) 401', async () => {
    const token = await mintIdToken({ kid: 'nonexistent-kid-9999' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T11: HS256 algorithm rejected 401', async () => {
    const { importJWK } = await import('jose');
    const secret = new TextEncoder().encode('hs256-secret-key-must-be-long-enough-32ch');
    const key = await importJWK({ kty: 'oct', k: Buffer.from(secret).toString('base64url') }, 'HS256');
    const token = await new SignJWT({ token_use: 'id', email: 'test@example.com' })
      .setProtectedHeader({ alg: 'HS256', kid: kidA })
      .setSubject('cognito-sub-real-123')
      .setIssuer(TEST_ISSUER)
      .setAudience(TEST_CLIENT_ID)
      .setIssuedAt()
      .setExpirationTime('5m')
      .sign(key);
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });
});
