// Auto-generated by CHORE-006 implementation
import { describe, it, expect, jest, beforeAll, afterAll } from '@jest/globals';
import Fastify, { FastifyInstance } from 'fastify';
import rateLimit from '@fastify/rate-limit';
import { SignJWT, generateKeyPair, exportJWK, createLocalJWKSet, jwtVerify, type JWK } from 'jose';
import type pg from 'pg';
import { UnauthorizedError } from '@celebbase/service-core';
import type { AuthProvider, AuthTokens, AuthTokenSubject, IdTokenPayload } from '../../src/services/auth.service.js';
import { issueInternalTokens } from '../../src/services/auth.service.js';

// ── 저장소 mock ──────────────────────────────────────────────

jest.unstable_mockModule('../../src/repositories/user.repository.js', () => ({
  findByCognitoSub: jest.fn(),
  findByEmail: jest.fn(),
  findAndUpdateCognitoSubByEmail: jest.fn(),
  create: jest.fn(),
  updateCognitoSub: jest.fn(),
}));
jest.unstable_mockModule('../../src/repositories/refresh-token.repository.js', () => ({
  insert: jest.fn(),
  revokeForRotation: jest.fn(),
  findMetadata: jest.fn(),
  revokeForLogout: jest.fn(),
  revokeChainForLogout: jest.fn(),
  revokeAllByUser: jest.fn(),
}));

const { authRoutes } = await import('../../src/routes/auth.routes.js');
const userRepo = await import('../../src/repositories/user.repository.js');
const refreshTokenRepo = await import('../../src/repositories/refresh-token.repository.js');

// ── 로컬 JWKS 세팅 ───────────────────────────────────────────

const TEST_ISSUER = 'https://cognito-idp.us-west-2.amazonaws.com/us-west-2_TESTPOOL';
const TEST_CLIENT_ID = 'test-client-id';

let privateKeyA: CryptoKey;
let publicKeyA: CryptoKey;
let kidA: string;
let privateKeyB: CryptoKey;
let kidB: string;
let localJwks: ReturnType<typeof createLocalJWKSet>;

beforeAll(async () => {
  const pairA = await generateKeyPair('RS256');
  privateKeyA = pairA.privateKey;
  publicKeyA = pairA.publicKey;

  const pairB = await generateKeyPair('RS256');
  privateKeyB = pairB.privateKey;

  kidA = 'key-a';
  kidB = 'key-b';

  const jwkA = { ...(await exportJWK(publicKeyA)), kid: kidA } as JWK;
  const jwkB = { ...(await exportJWK(pairB.publicKey)), kid: kidB } as JWK;
  localJwks = createLocalJWKSet({ keys: [jwkA, jwkB] });
});

class LocalCognitoTestProvider implements AuthProvider {

  async verifyIdToken(idToken: string): Promise<IdTokenPayload> {
    try {
      const { payload } = await jwtVerify(idToken, localJwks, {
        issuer: TEST_ISSUER,
        audience: TEST_CLIENT_ID,
        algorithms: ['RS256'],
        clockTolerance: 60,
      });
      if (payload['token_use'] !== 'id') {
        throw new UnauthorizedError('Expected id token');
      }
      if (typeof payload.sub !== 'string' || !payload.sub) {
        throw new UnauthorizedError('Missing sub claim');
      }
      if (typeof payload['email'] !== 'string' || !payload['email']) {
        throw new UnauthorizedError('Missing email claim');
      }
      return { sub: payload.sub, email: payload['email'] as string };
    } catch (err) {
      if (err instanceof UnauthorizedError) throw err;
      throw new UnauthorizedError('Invalid or expired id token');
    }
  }

  async issueTokens(_client: pg.Pool | pg.PoolClient, subject: AuthTokenSubject): Promise<AuthTokens> {
    return issueInternalTokens({} as pg.Pool, subject);
  }
}

interface CapturedLog { event?: string; [key: string]: unknown; }

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function makeCaptureLogger(captured: CapturedLog[]): any {
  const logger = {
    level: 'info',
    silent: () => undefined,
    info: (obj: unknown): void => {
      if (typeof obj === 'object' && obj !== null) captured.push(obj as CapturedLog);
    },
    warn: (obj: unknown): void => {
      if (typeof obj === 'object' && obj !== null) captured.push(obj as CapturedLog);
    },
    error: () => undefined,
    debug: () => undefined,
    trace: () => undefined,
    fatal: () => undefined,
    child: () => logger,
  };
  return logger;
}

async function buildApp(provider: AuthProvider): Promise<FastifyInstance> {
  const captured: CapturedLog[] = [];
  const app = Fastify({
    loggerInstance: makeCaptureLogger(captured),
    disableRequestLogging: true,
  });
  await app.register(rateLimit, { global: false });
  await app.register(authRoutes, {
    pool: {} as pg.Pool,
    authProvider: provider,
  });
  return app;
}

async function mintIdToken(overrides: {
  kid?: string;
  issuer?: string;
  audience?: string;
  tokenUse?: string;
  sub?: string;
  email?: string;
  expiresIn?: string | number;
  privateKey?: CryptoKey;
} = {}): Promise<string> {
  const {
    kid = kidA,
    issuer = TEST_ISSUER,
    audience = TEST_CLIENT_ID,
    tokenUse = 'id',
    sub = 'cognito-sub-real-123',
    email = 'test@example.com',
    expiresIn = '5m',
    privateKey = privateKeyA,
  } = overrides;

  return new SignJWT({ token_use: tokenUse, email })
    .setProtectedHeader({ alg: 'RS256', kid })
    .setSubject(sub)
    .setIssuer(issuer)
    .setAudience(audience)
    .setIssuedAt()
    .setExpirationTime(expiresIn)
    .sign(privateKey);
}

// ── 테스트 케이스 ─────────────────────────────────────────────────────────

describe('Cognito AuthProvider Integration', () => {
  let app: FastifyInstance;
  beforeAll(async () => {
    const provider = new LocalCognitoTestProvider();
    app = await buildApp(provider);
    await app.ready();
  });
  afterAll(async () => {
    await app.close();
  });

  it('T1: valid id_token login', async () => {
    const token = await mintIdToken();
    (userRepo.findByCognitoSub as jest.Mock).mockResolvedValueOnce({
      id: 'user-id-1',
      email: 'test@example.com',
      cognito_sub: 'cognito-sub-real-123',
      display_name: 'Test',
      deleted_at: null,
    });
    (refreshTokenRepo.insert as jest.Mock).mockResolvedValueOnce(undefined);
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(200);
    const body = res.json();
    expect(body).toHaveProperty('access_token');
    expect(body).toHaveProperty('refresh_token');
  });

  it('T2: access_token should 401', async () => {
    const token = await mintIdToken({ tokenUse: 'access' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T3: expired token 401', async () => {
    const past = Math.floor(Date.now() / 1000) - 200;
    const token = await mintIdToken({ expiresIn: past });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T4: wrong issuer 401', async () => {
    const token = await mintIdToken({ issuer: 'https://fake-issuer.example.com' });
    const res = await app.inject({
      method: 'POST',
      url: '/auth/login',
      payload: { email: 'test@example.com', id_token: token },
    });
    expect(res.statusCode).toBe(401);
  });

  it('T5: kid rotation both succeed', async () => {
    const tokenB = await mintIdToken({ kid: kidB, privateKey: privateKeyB });
    (userRepo.findByCognitoSub as jest.Mock).mockResolvedValue({ id: 'x', email: 'test@example.com', cognito_sub: 'cognito-sub-real-123', display_name: 'Test', deleted_at: null });
    (refreshTokenRepo.insert as jest.Mock).mockResolvedValue(undefined);
    let res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenB } });
    expect(res.statusCode).toBe(200);

    const tokenA = await mintIdToken({ kid: kidA });
    res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenA } });
    expect(res.statusCode).toBe(200);
  });

  it('T6: clock skew tolerance', async () => {
    const expMinus30 = Math.floor(Date.now() / 1000) - 30;
    const tokenNear = await mintIdToken({ expiresIn: expMinus30 });
    let res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenNear } });
    expect(res.statusCode).toBe(200);

    const expMinus70 = Math.floor(Date.now() / 1000) - 70;
    const tokenFar = await mintIdToken({ expiresIn: expMinus70 });
    res = await app.inject({ method: 'POST', url: '/auth/login', payload: { email: 'test@example.com', id_token: tokenFar } });
    expect(res.statusCode).toBe(401);
  });
});
