// Parse tokens.css -> emit tokens.native.ts with typed light/dark maps for JS consumers.
// Invoked by `pnpm --filter @celebbase/design-tokens build` before tsc.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..');
const SOURCE_CSS = join(PACKAGE_ROOT, 'tokens.css');
const OUTPUT_TS = join(PACKAGE_ROOT, 'src', 'tokens.native.ts');

type TokenMap = Record<string, string>;

function parseBlock(css: string, selector: string): TokenMap {
  const selectorIdx = css.indexOf(selector);
  if (selectorIdx === -1) {
    throw new Error(`Selector "${selector}" not found in tokens.css`);
  }
  const openBrace = css.indexOf('{', selectorIdx);
  const closeBrace = css.indexOf('}', openBrace);
  if (openBrace === -1 || closeBrace === -1) {
    throw new Error(`Malformed block for selector "${selector}"`);
  }
  const body = css.slice(openBrace + 1, closeBrace);
  const map: TokenMap = {};
  for (const rawLine of body.split('\n')) {
    const line = rawLine.replace(/\/\*.*?\*\//g, '').trim();
    if (!line.startsWith('--')) continue;
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const name = line.slice(0, colonIdx).trim();
    const value = line.slice(colonIdx + 1).replace(/;$/, '').trim();
    if (!name || !value) continue;
    map[name] = value;
  }
  return map;
}

function formatMap(map: TokenMap, indent = '  '): string {
  const keys = Object.keys(map).sort();
  const entries = keys.map((k) => `${indent}'${k}': '${map[k]!.replace(/'/g, "\\'")}',`);
  return `{\n${entries.join('\n')}\n}`;
}

function main(): void {
  const css = readFileSync(SOURCE_CSS, 'utf8');
  const light = parseBlock(css, ':root');
  const darkOverrides = parseBlock(css, "[data-theme='dark']");

  if (Object.keys(light).length === 0) {
    throw new Error('Light theme token map is empty — check tokens.css');
  }

  // CSS cascade: dark inherits every token from :root, then overrides apply.
  // Mirror that in the JS map so every TokenName indexes into both themes.
  const dark: TokenMap = { ...light, ...darkOverrides };

  const header = `// AUTO-GENERATED by packages/design-tokens/scripts/build.ts — do not edit by hand.
// Regenerate with: pnpm --filter @celebbase/design-tokens build
`;

  const body = `export const tokens = {
  light: ${formatMap(light, '    ')},
  dark: ${formatMap(dark, '    ')},
} as const;

export type TokenName = keyof (typeof tokens)['light'];

export function getToken(theme: 'light' | 'dark', name: TokenName): string {
  return tokens[theme][name];
}
`;

  writeFileSync(OUTPUT_TS, `${header}\n${body}`, 'utf8');
  process.stdout.write(
    `[design-tokens] emitted tokens.native.ts (light=${Object.keys(light).length}, dark=${Object.keys(dark).length}, overrides=${Object.keys(darkOverrides).length})\n`,
  );
}

main();
