// Parse tokens.css -> emit tokens.native.ts with typed light/dark maps for JS consumers.
// Invoked by `pnpm --filter @celebbase/design-tokens build` before tsc.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..');
const SOURCE_CSS = join(PACKAGE_ROOT, 'tokens.css');
const OUTPUT_TS = join(PACKAGE_ROOT, 'src', 'tokens.native.ts');

type TokenMap = Record<string, string>;

function parseBlock(css: string, selector: string): TokenMap {
  const selectorIdx = css.indexOf(selector);
  if (selectorIdx === -1) {
    throw new Error(`Selector "${selector}" not found in tokens.css`);
  }
  const openBrace = css.indexOf('{', selectorIdx);
  const closeBrace = css.indexOf('}', openBrace);
  if (openBrace === -1 || closeBrace === -1) {
    throw new Error(`Malformed block for selector "${selector}"`);
  }
  const body = css.slice(openBrace + 1, closeBrace);
  const map: TokenMap = {};
  // Strip block comments first (multi-line safe), then split on ';' — the CSS
  // declaration separator. Splitting on '\n' (the old approach) swallowed every
  // declaration after the first on a multi-declaration line into the first
  // one's value (e.g. "--cb-danger-600: X;  --cb-danger-100: Y;" lost -100 and
  // corrupted -600). CSS values never contain a bare ';', so this is safe.
  const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const rawDecl of withoutComments.split(';')) {
    const decl = rawDecl.trim();
    if (!decl.startsWith('--')) continue;
    const colonIdx = decl.indexOf(':');
    if (colonIdx === -1) continue;
    const name = decl.slice(0, colonIdx).trim();
    const value = decl.slice(colonIdx + 1).trim();
    if (!name || !value) continue;
    map[name] = value;
  }
  return map;
}

function formatMap(map: TokenMap, indent = '  '): string {
  const entries = Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `${indent}'${k}': '${v.replace(/'/g, "\\'")}',`);
  return `{\n${entries.join('\n')}\n}`;
}

function main(): void {
  const css = readFileSync(SOURCE_CSS, 'utf8');
  const light = parseBlock(css, ':root');
  const darkOverrides = parseBlock(css, "[data-theme='dark']");

  if (Object.keys(light).length === 0) {
    throw new Error('Light theme token map is empty — check tokens.css');
  }

  // CSS cascade: dark inherits every token from :root, then overrides apply.
  // Mirror that in the JS map so every TokenName indexes into both themes.
  const dark: TokenMap = { ...light, ...darkOverrides };

  const header = `// AUTO-GENERATED by packages/design-tokens/scripts/build.ts — do not edit by hand.
// Regenerate with: pnpm --filter @celebbase/design-tokens build
`;

  const body = `export const tokens = {
  light: ${formatMap(light, '    ')},
  dark: ${formatMap(dark, '    ')},
} as const;

export type TokenName = keyof (typeof tokens)['light'];

export function getToken(theme: 'light' | 'dark', name: TokenName): string {
  return tokens[theme][name];
}
`;

  writeFileSync(OUTPUT_TS, `${header}\n${body}`, 'utf8');
  const lightCount = String(Object.keys(light).length);
  const darkCount = String(Object.keys(dark).length);
  const overrideCount = String(Object.keys(darkOverrides).length);
  process.stdout.write(
    `[design-tokens] emitted tokens.native.ts (light=${lightCount}, dark=${darkCount}, overrides=${overrideCount})\n`,
  );
}

main();
