"""Repository layer for meal_plans table.

All queries use parameterized placeholders ($1, $2, …) — no string
concatenation.  UUIDs are generated via the ``uuid7`` package.
Soft-delete is enforced by filtering ``deleted_at IS NULL``.
"""
from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

import asyncpg

_logger = logging.getLogger(__name__)


async def create_meal_plan(
    pool: asyncpg.Pool,
    user_id: str,
    base_diet_id: str,
    duration_days: int,
    preferences: Dict[str, Any],
) -> Dict[str, Any]:
    """Insert a new meal plan with status ``queued``."""

    # UUID v7 generated by DB default (uuid_generate_v7()) — no app-layer UUID needed
    row = await pool.fetchrow(
        """
        INSERT INTO meal_plans (user_id, base_diet_id, duration_days, preferences, status)
        VALUES ($1, $2, $3, $4::jsonb, 'queued')
        RETURNING *
        """,
        user_id,
        base_diet_id,
        duration_days,
        json.dumps(preferences),
    )
    return dict(row) if row else {}


async def get_meal_plan(
    pool: asyncpg.Pool,
    plan_id: str,
    user_id: str,
) -> Optional[Dict[str, Any]]:
    """Fetch a single meal plan owned by *user_id*."""

    row = await pool.fetchrow(
        """
        SELECT * FROM meal_plans
        WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
        """,
        plan_id,
        user_id,
    )
    return dict(row) if row else None


async def list_meal_plans(
    pool: asyncpg.Pool,
    user_id: str,
    cursor: Optional[str],
    limit: int,
) -> List[Dict[str, Any]]:
    """Return meal plans with cursor-based pagination.

    Fetches ``limit + 1`` rows so the caller can derive ``has_next``.
    """

    if cursor is not None:
        rows = await pool.fetch(
            """
            SELECT * FROM meal_plans
            WHERE user_id = $1 AND id > $2 AND deleted_at IS NULL
            ORDER BY id ASC
            LIMIT $3
            """,
            user_id,
            cursor,
            limit + 1,
        )
    else:
        rows = await pool.fetch(
            """
            SELECT * FROM meal_plans
            WHERE user_id = $1 AND deleted_at IS NULL
            ORDER BY id ASC
            LIMIT $2
            """,
            user_id,
            limit + 1,
        )
    return [dict(r) for r in rows]


async def update_meal_plan(
    pool: asyncpg.Pool,
    plan_id: str,
    user_id: str,
    updates: Dict[str, Any],
) -> Optional[Dict[str, Any]]:
    """Apply a partial update to a meal plan.

    Only keys present in *updates* are written.  The function builds
    parameterized SET clauses dynamically — no string interpolation of
    user data.
    """

    if not updates:
        return await get_meal_plan(pool, plan_id, user_id)

    allowed_columns = {"status", "daily_plans", "adjustments", "preferences", "duration_days"}
    filtered = {k: v for k, v in updates.items() if k in allowed_columns}
    if not filtered:
        return await get_meal_plan(pool, plan_id, user_id)

    set_parts: list[str] = []
    values: list[Any] = []
    idx = 1

    for col, val in filtered.items():
        if col in ("daily_plans", "adjustments", "preferences"):
            set_parts.append(f"{col} = ${idx}::jsonb")
            values.append(json.dumps(val) if not isinstance(val, str) else val)
        else:
            set_parts.append(f"{col} = ${idx}")
            values.append(val)
        idx += 1

    set_parts.append("updated_at = NOW()")

    values.append(plan_id)
    values.append(user_id)

    sql = f"""
        UPDATE meal_plans
        SET {', '.join(set_parts)}
        WHERE id = ${idx} AND user_id = ${idx + 1} AND deleted_at IS NULL
        RETURNING *
    """

    row = await pool.fetchrow(sql, *values)
    return dict(row) if row else None


async def archive_meal_plan(
    pool: asyncpg.Pool,
    plan_id: str,
    user_id: str,
) -> bool:
    """Soft-delete a meal plan by setting ``deleted_at``."""

    result = await pool.execute(
        """
        UPDATE meal_plans
        SET deleted_at = NOW(), updated_at = NOW()
        WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
        """,
        plan_id,
        user_id,
    )
    return result == "UPDATE 1"
